// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1mnCbpgI4O6HoGeZwEEDfyXL9gsB_tI4',
    appId: '1:615760504353:web:ce8504524f735bdee56560',
    messagingSenderId: '615760504353',
    projectId: 'tic-tok-abc',
    authDomain: 'tic-tok-abc.firebaseapp.com',
    storageBucket: 'tic-tok-abc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByONsm5wZkmH4WZu4riowWvh7372a2bag',
    appId: '1:615760504353:android:7dcfd70f538f446be56560',
    messagingSenderId: '615760504353',
    projectId: 'tic-tok-abc',
    storageBucket: 'tic-tok-abc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRXzfKm_dK7gZPbWlCmsmJc1gKmBvjJg4',
    appId: '1:615760504353:ios:281594a283fba9cbe56560',
    messagingSenderId: '615760504353',
    projectId: 'tic-tok-abc',
    storageBucket: 'tic-tok-abc.appspot.com',
    iosBundleId: 'com.example.tictokClone',
  );

}